; SMT-LIB formulae selfie-generated by ./selfie
; for manuscript/code/symbolic/nested-if-else.c with 300 execution depth

(set-option :produce-models true)
(set-option :incremental true)
(set-logic QF_BV)

(declare-fun r0 () (_ BitVec 8)); variable for manuscript/code/symbolic/nested-if-else.c: $pc=0x1007C(~1): 
(declare-fun b1 () (_ BitVec 1)); variable for manuscript/code/symbolic/nested-if-else.c: $pc=0x101B0(~21): 
(assert (= b1 (bvcomp ((_ zero_extend 63) (bvult (_ bv42 64) ((_ zero_extend 56) r0))) (_ bv0 64)))); beq in manuscript/code/symbolic/nested-if-else.c: $pc=0x101B0(~21): 
(declare-fun p2 () (_ BitVec 1)); variable for manuscript/code/symbolic/nested-if-else.c: $pc=0x101B0(~21): 
(assert (= p2 true)); path condition in manuscript/code/symbolic/nested-if-else.c: $pc=0x101B0(~21): 
(declare-fun m3 () (_ BitVec 64)); variable for manuscript/code/symbolic/nested-if-else.c: $pc=0x101C8(~22): 
(assert (= m3 (bvsub ((_ zero_extend 56) r0) (_ bv1 64)))); sd in manuscript/code/symbolic/nested-if-else.c: $pc=0x101C8(~22): 
(declare-fun b4 () (_ BitVec 1)); variable for manuscript/code/symbolic/nested-if-else.c: $pc=0x101DC(~24): 
(assert (= b4 (bvcomp ((_ zero_extend 63) (bvult (_ bv50 64) m3)) (_ bv0 64)))); beq in manuscript/code/symbolic/nested-if-else.c: $pc=0x101DC(~24): 
(declare-fun p5 () (_ BitVec 1)); variable for manuscript/code/symbolic/nested-if-else.c: $pc=0x101DC(~24): 
(assert (= p5 (and p2 (not b1)))); path condition in manuscript/code/symbolic/nested-if-else.c: $pc=0x101DC(~24): 
(declare-fun m6 () (_ BitVec 64)); variable for manuscript/code/symbolic/nested-if-else.c: $pc=0x101F4(~25): 
(assert (= m6 (bvsub m3 (_ bv1 64)))); sd in manuscript/code/symbolic/nested-if-else.c: $pc=0x101F4(~25): 
(declare-fun m7 () (_ BitVec 64)); variable for manuscript/code/symbolic/nested-if-else.c: $pc=0x10210(~27): 
(assert (= m7 (bvadd m3 (_ bv1 64)))); sd in manuscript/code/symbolic/nested-if-else.c: $pc=0x10210(~27): 
; merge possible at manuscript/code/symbolic/nested-if-else.c: $pc=0x10214(~29): 
(declare-fun m8 () (_ BitVec 64)); variable for manuscript/code/symbolic/nested-if-else.c: $pc=0x1022C(~29): 
(assert (= m8 (bvadd ((_ zero_extend 56) r0) (_ bv10 64)))); sd in manuscript/code/symbolic/nested-if-else.c: $pc=0x1022C(~29): 
; merge possible at manuscript/code/symbolic/nested-if-else.c: $pc=0x10230(~31): 
(declare-fun b9 () (_ BitVec 1)); variable for manuscript/code/symbolic/nested-if-else.c: $pc=0x10248(~31): 
(assert (= b9 (bvcomp ((_ zero_extend 63) (bvult (bvsub (_ bv50 64) m8) (_ bv1 64))) (_ bv0 64)))); beq in manuscript/code/symbolic/nested-if-else.c: $pc=0x10248(~31): 
(declare-fun p10 () (_ BitVec 1)); variable for manuscript/code/symbolic/nested-if-else.c: $pc=0x10248(~31): 
(assert (= p10 (and p2 b1))); path condition in manuscript/code/symbolic/nested-if-else.c: $pc=0x10248(~31): 
; merge possible at manuscript/code/symbolic/nested-if-else.c: $pc=0x10268(~35): 

(push 1)
(assert (and (and p10 b9) (not (= (_ bv0 64) (_ bv0 64))))); exit in manuscript/code/symbolic/nested-if-else.c: $pc=0x1005C(~1): 
(check-sat)
(get-model)
(pop 1)

(push 1)
(assert (and (and p10 (not b9)) (not (= (_ bv1 64) (_ bv0 64))))); exit in manuscript/code/symbolic/nested-if-else.c: $pc=0x1005C(~1): 
(check-sat)
(get-model)
(pop 1)
(declare-fun b11 () (_ BitVec 1)); variable for manuscript/code/symbolic/nested-if-else.c: $pc=0x10248(~31): 
(assert (= b11 (bvcomp ((_ zero_extend 63) (bvult (bvsub (_ bv50 64) m7) (_ bv1 64))) (_ bv0 64)))); beq in manuscript/code/symbolic/nested-if-else.c: $pc=0x10248(~31): 
(declare-fun p12 () (_ BitVec 1)); variable for manuscript/code/symbolic/nested-if-else.c: $pc=0x10248(~31): 
(assert (= p12 (and p5 b4))); path condition in manuscript/code/symbolic/nested-if-else.c: $pc=0x10248(~31): 
; merge possible at manuscript/code/symbolic/nested-if-else.c: $pc=0x10268(~35): 

(push 1)
(assert (and (and p12 b11) (not (= (_ bv0 64) (_ bv0 64))))); exit in manuscript/code/symbolic/nested-if-else.c: $pc=0x1005C(~1): 
(check-sat)
(get-model)
(pop 1)

(push 1)
(assert (and (and p12 (not b11)) (not (= (_ bv1 64) (_ bv0 64))))); exit in manuscript/code/symbolic/nested-if-else.c: $pc=0x1005C(~1): 
(check-sat)
(get-model)
(pop 1)
(declare-fun b13 () (_ BitVec 1)); variable for manuscript/code/symbolic/nested-if-else.c: $pc=0x10248(~31): 
(assert (= b13 (bvcomp ((_ zero_extend 63) (bvult (bvsub (_ bv50 64) m6) (_ bv1 64))) (_ bv0 64)))); beq in manuscript/code/symbolic/nested-if-else.c: $pc=0x10248(~31): 
(declare-fun p14 () (_ BitVec 1)); variable for manuscript/code/symbolic/nested-if-else.c: $pc=0x10248(~31): 
(assert (= p14 (and p5 (not b4)))); path condition in manuscript/code/symbolic/nested-if-else.c: $pc=0x10248(~31): 
; merge possible at manuscript/code/symbolic/nested-if-else.c: $pc=0x10268(~35): 

(push 1)
(assert (and (and p14 b13) (not (= (_ bv0 64) (_ bv0 64))))); exit in manuscript/code/symbolic/nested-if-else.c: $pc=0x1005C(~1): 
(check-sat)
(get-model)
(pop 1)

(push 1)
(assert (and (and p14 (not b13)) (not (= (_ bv1 64) (_ bv0 64))))); exit in manuscript/code/symbolic/nested-if-else.c: $pc=0x1005C(~1): 
(check-sat)
(get-model)
(pop 1)

(exit)