; SMT-LIB formulae selfie-generated by ./selfie
; for manuscript/code/merge/simple-if-else.c with 300 execution depth

(set-option :produce-models true)
(set-option :incremental true)
(set-logic QF_BV)

(declare-fun r0 () (_ BitVec 8)); variable for manuscript/code/merge/simple-if-else.c: $pc=0x1007C(~1): 
(declare-fun b1 () (_ BitVec 1)); variable for manuscript/code/merge/simple-if-else.c: $pc=0x101B8(~20): 
(assert (= b1 (bvcomp ((_ zero_extend 63) (bvult (bvsub (_ bv2 64) ((_ zero_extend 56) r0)) (_ bv1 64))) (_ bv0 64)))); beq in manuscript/code/merge/simple-if-else.c: $pc=0x101B8(~20): 
(declare-fun p2 () (_ BitVec 1)); variable for manuscript/code/merge/simple-if-else.c: $pc=0x101B8(~20): 
(assert (= p2 true)); path condition in manuscript/code/merge/simple-if-else.c: $pc=0x101B8(~20): 
(declare-fun m3 () (_ BitVec 64)); variable for manuscript/code/merge/simple-if-else.c: $pc=0x101CC(~21): 
(assert (= m3 (bvadd (_ bv40 64) ((_ zero_extend 56) r0)))); sd in manuscript/code/merge/simple-if-else.c: $pc=0x101CC(~21): 
; merge potentially possible at instruction: manuscript/code/merge/simple-if-else.c: $pc=0x101F0(~25): 
(declare-fun b4 () (_ BitVec 1)); variable for manuscript/code/merge/simple-if-else.c: $pc=0x10204(~25): 
(assert (= b4 (bvcomp ((_ zero_extend 63) (bvult (bvsub (_ bv42 64) m3) (_ bv1 64))) (_ bv0 64)))); beq in manuscript/code/merge/simple-if-else.c: $pc=0x10204(~25): 
(declare-fun p5 () (_ BitVec 1)); variable for manuscript/code/merge/simple-if-else.c: $pc=0x10204(~25): 
(assert (= p5 (and p2 (not b1)))); path condition in manuscript/code/merge/simple-if-else.c: $pc=0x10204(~25): 
; merge potentially possible at instruction: manuscript/code/merge/simple-if-else.c: $pc=0x10224(~29): 

(push 1)
(assert (and (and p5 (not b4)) (not (= (_ bv1 64) (_ bv0 64))))); exit in manuscript/code/merge/simple-if-else.c: $pc=0x1005C(~1): 
(check-sat)
(get-model)
(pop 1)

(push 1)
(assert (and (and p5 b4) (not (= (_ bv0 64) (_ bv0 64))))); exit in manuscript/code/merge/simple-if-else.c: $pc=0x1005C(~1): 
(check-sat)
(get-model)
(pop 1)
(declare-fun m6 () (_ BitVec 64)); variable for manuscript/code/merge/simple-if-else.c: $pc=0x101EC(~23): 
(assert (= m6 (bvadd (_ bv40 64) (bvsub ((_ zero_extend 56) r0) (_ bv10 64))))); sd in manuscript/code/merge/simple-if-else.c: $pc=0x101EC(~23): 
(declare-fun b7 () (_ BitVec 1)); variable for manuscript/code/merge/simple-if-else.c: $pc=0x10204(~25): 
(assert (= b7 (bvcomp ((_ zero_extend 63) (bvult (bvsub (_ bv42 64) m6) (_ bv1 64))) (_ bv0 64)))); beq in manuscript/code/merge/simple-if-else.c: $pc=0x10204(~25): 
(declare-fun p8 () (_ BitVec 1)); variable for manuscript/code/merge/simple-if-else.c: $pc=0x10204(~25): 
(assert (= p8 (and p2 b1))); path condition in manuscript/code/merge/simple-if-else.c: $pc=0x10204(~25): 
; merge potentially possible at instruction: manuscript/code/merge/simple-if-else.c: $pc=0x10224(~29): 

(push 1)
(assert (and (and p8 (not b7)) (not (= (_ bv1 64) (_ bv0 64))))); exit in manuscript/code/merge/simple-if-else.c: $pc=0x1005C(~1): 
(check-sat)
(get-model)
(pop 1)

(push 1)
(assert (and (and p8 b7) (not (= (_ bv0 64) (_ bv0 64))))); exit in manuscript/code/merge/simple-if-else.c: $pc=0x1005C(~1): 
(check-sat)
(get-model)
(pop 1)

(exit)